#
site_name: "SADIE"
site_description: "SADIE: Seuqencing Analysis and Data Library for Immunoinformatics Exploration"
site_url: https://sadie.jordanrwillis.com/
og_image: https://repository-images.githubusercontent.com/313568721/5adf0900-c0d7-11eb-921d-36288bd44b7c
theme:
  name: material
  custom_dir: docs/overrides
  icon:
    logo: material/dog
  favicon: img/favico.png
  palette:
  - scheme: default
    primary: white
    accent: amber
    toggle:
      icon: material/weather-night
      name: Switch to night mode
  - scheme: slate
    primary: black
    accent: red
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
  features: # look for feature flag in documentation
    - search.suggest
    - search.highlight
    - content.tabs.link
    - search.share
    - navigation.tracking
    - navigation.tabs.sticky
  icon:
    repo: fontawesome/brands/github-alt
repo_name: jwillis0720/sadie
repo_url: https://github.com/jwillis0720/sadie
plugins: #  look for plugins tag in material markdown documentation
  - search
markdown_extensions: #
  - admonition # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#admonition
  - toc: # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#table-of-contents
      permalink: true
  - pymdownx.highlight: #https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#highlight
      linenums: false
      use_pygments: true
  - pymdownx.superfences:  #https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#superfences
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - mdx_include: # pip install mdx-include
      base_path: docs/
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav: # this is how we layout the documents
  - SADIE: index.md
  - Reference Database: reference.md
  - AIRR Sequence Annotation:
    - Annotating: annotation.md
    # - Advanced Annotation Methods: advanced_annotation.md  # TODO: add to_datafarme a few other hidden methods
  - Sequence Numbering: renumbering.md
  - BCR/TCR Objects: models.md
  - Clustering: clustering.md
  - Contributing to SADIE: contribute.md
extra_css:
  - css/termynal.css
  - css/custom.css
extra_javascript:
  - https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js
  - js/termynal.js
  - js/custom.js
extra:
  social:
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/jwillis0720
  - icon: fontawesome/brands/github-alt
    link: https://github.com/jwillis0720/sadie
