#
site_name: "SADIE"
site_description: "SADIE: Seuqencing Analysis and Data Library for Immunoinformatics Exploration"
site_url: https://sadie.jordanrwillis.com/
og_image: https://repository-images.githubusercontent.com/313568721/5adf0900-c0d7-11eb-921d-36288bd44b7c
theme:
  name: material
  custom_dir: docs/overrides
  icon:
    logo: material/dog
    # logo: fontawesome/solid/do
  favicon: img/favico.png
  palette:
  - scheme: default
    primary: white
    accent: amber
    toggle:
      icon: material/weather-night
      name: Switch to night mode
  - scheme: slate
    primary: black
    accent: red
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
repo_name: jwillis0720/sadie
repo_url: https://github.com/jwillis0720/sadie
plugins:
- search
- git-revision-date
markdown_extensions:
- toc:
    permalink: true
- markdown.extensions.codehilite:
    guess_lang: false
- markdown_include.include:
    base_path: docs
- admonition
- codehilite
- extra
- meta
- pymdownx.snippets
- codehilite
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_div_format ''
- pymdownx.tabbed
nav:
- SADIE: index.md
extra_css:
- css/termynal.css
- css/custom.css
extra_javascript:
- https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js
- js/termynal.js
- js/custom.js
