#
site_name: SADIE
site_description: SADIE:Sequencing Analysis and Data library for Immunoinformatics Exploration
site_url: http://sadie.jordanrwillis.com/
theme:
  name: material
  palette:
  - scheme: default
    primary: white
    accent: amber
    toggle:
      icon: material/weather-night
      name: Switch to night mode
  - scheme: slate
    primary: black
    accent: red
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
repo_name: jwillis0720/sadie
repo_url: https://github.com/jwillis0720/sadie
plugins:
- search
markdown_extensions:
  - abbr
  - codehilite
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown_include.include:
      base_path: docs
  - admonition
  - codehilite
  - extra
  - pymdownx.snippets

nav:
- SADIE: index.md
