[mypy]
plugins = pydantic.mypy

# these are explicit strict defs
disallow_any_generics = True
warn_unused_configs = True
disallow_subclassing_any = True
disallow_untyped_calls =True
disallow_untyped_defs = True
disallow_incomplete_defs = True
check_untyped_defs = True
disallow_untyped_decorators = True
no_implicit_optional = True
warn_redundant_casts = True
warn_unused_ignores=True
warn_return_any = True
no_implicit_reexport=True
strict_equality = True
follow_imports = silent
pretty = True
show_error_codes=True


[pydantic-mypy] # https://pydantic-docs.helpmanual.io/mypy_plugin/#enabling-the-plugin
init_forbid_extra = True
init_typed = True
warn_required_dynamic_aliases = True
warn_untyped_fields = True

[mypy-semantic_version.*]
ignore_missing_imports = True

[mypy-filetype.*]
ignore_missing_imports = True

[mypy-Levenshtein.*]
ignore_missing_imports = True

[mypy-sadie.airr.airrtable.*]
ignore_errors = True

[mypy-sadie.renumbering.*]
ignore_errors = True

[mypy-sadie.antibody.*]
ignore_errors = True

[mypy-sadie.numbering.*]
ignore_errors = True

[tool.pyright]
exclude = ['src/sadie/renumbering/*', 'src/sadie/numbering/*']
include = ['src/sadie']
reportUnnecessaryIsInstance = false
stubsPath = 'src/stubs'
