# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Build and Test
on:
  push:
    tags:
    - '*'
    branches: ['master']
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7,3.8,3.9]
    env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
            python-version: ${{ matrix.python-version }}
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install w/dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install coverage
          pip install .
      - name : Cache PIP
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: PreCommit
        uses: pre-commit/action@v2.0.0
      - name: Test
        run: |
          env
          ./scripts/run_coverage_and_test.sh
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: ./coverage
      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
        with:
          directory: ./coverage/reports/xml
          name: codecov-umbrella
          verbose: true
      - name: Install Twine and Build Wheel
        # if: startsWith(github.ref, 'refs/tags/v')
        run: |
         pip install wheel twine setuptools
         python setup.py sdist bdist_wheel --universal
      - name: Publish distribution to PyPi
        # if: startsWith(github.ref, 'refs/tags/v')
        run: |
          twine upload --repository pypi dist/*
          twine upload --repository testpypi dist/*.tar.gz
