name: Static Type Check
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "development"]
jobs:
  check_static:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry lock --no-update
          poetry install --with dev
      - run: mypy src/sadie
