name: Static Type Check
on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main']
jobs:
  check_static:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: |
          pip install .
          pip install mypy==0.941
      - run: sh ./scripts/check_mypy.sh
