# Takes tag and auto sets that to the version to push to pypi
# Example:
# > git tag 0.1.1
# > git push --tags
name: Publish to PYPI

on:
  push:
    tags:
      - "*"
    branches: ["main"]

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: pip install poetry
      - name: Build and publish
        run: |
          poetry version $(git describe --tags --abbrev=0)
          poetry build
          poetry publish --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }}
