name: Linux Build and Test
on:
  push:
    tags:
      - "*"
    branches: ["main"]
  pull_request:
    branches: ["main", "development"]
jobs:
  linux-build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, "macos-latest"]
        python-version: [3.8, 3.9, "3.10"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          # cache: "poetry"
      - name: PreCommit
        uses: pre-commit/action@v3.0.0
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --with dev
      - name: Unit Testing
        run: poetry run pytest -xsv tests/unit
      - name: Integration Testing
        run: poetry run pytest -xv tests/integration
