# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Python Package Stratified
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest]
        os: [ubuntu-latest, macos-latest]
        python-version: [3.6,3.7,3.8]
        # python-version: [3.8]
    steps: 
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
            python-version: ${{ matrix.python-version }}
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install w/dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install pytest-cov
          pip install .
      - name: Test
        run: |
          env
          coverage run --source=./sadie --concurrency=multiprocessing --branch -m pytest 
          coverage xml 
          coverage report
          # I can't get pytest plugin to work on github acitons
          # pytest --cov=/home/runner/work/sadie/sadie --cov-report=xml --cov-report=term tests/airr
          # cat ./coverage.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.15